sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

script:
  - npm run release
deploy:
  provider: heroku
  app: "react-redux-test-2"
  api_key:
    secure: "82d327c9-0022-4ad0-aaf7-fa0f6ae84921"

script: npm run test-coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
